# The URL the site will be built for
base_url = "https://dev.zcraft.fr"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "juice"

[extra]
juice_extra_menu = [
  { title = "Plugins", link = "/#bukkit-plugins" },
  { title = "Libraries", link = "/#libraries-for-developers" },
  { title = "Support", link = "/support" },
  { title = "GitHub", link = "https://github.com/zDevelopers", hover = "GitHub organization", icon = "github" },
]
juice_logo_name = "zDevelopers"
juice_logo_path = "logo.png"
